export const SAVE_LOGIN_INFO = 'SAVE_LOGIN_INFO';
export const USER_LOGOUT = 'USER_LOGOUT'
export const SET_SELECTED_PROCESS = 'SET_SELECTED_PROCESS'

export const USER_SIGNUP_INIT = 'USER_SIGNUP_INIT'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'


export const USER_LOGIN_INIT = 'USER_LOGIN_INIT'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'


export const  FETCH_USER_PERMISSION_INIT = 'FETCH_USER_PERMISSION_INIT'
export const  FETCH_USER_PERMISSION_SUCCESS = 'FETCH_USER_PERMISSION_SUCCESS'
export const FETCH_USER_PERMISSION_FAILURE = 'FETCH_USER_PERMISSION_FAILURE'

export const FETCH_LOGS_INIT = 'FETCH_LOGS_INIT'
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS'  
export const FETCH_LOGS_FAILURE = 'FETCH_LOGS_FAILURE'

export const FETCH_APPROVAL_INIT = 'FETCH_APPROVAL_INIT'
export const FETCH_APPROVAL_SUCCESS = 'FETCH_APPROVAL_SUCCESS'
export const FETCH_APPROVAL_FAILURE = 'FETCH_APPROVAL_FAILURE'


export const POST_NEW_REQUEST_INIT = 'POST_NEW_REQUEST_INIT'
export const POST_NEW_REQUEST_FAILED = 'POST_NEW_REQUEST_FAILED'
export const POST_NEW_REQUEST_SUCCESS = 'POST_NEW_REQUEST_SUCCESS'

export const GET_USER_LIST_INIT = 'GET_USER_LIST_INIT'
export const GET_USER_LIST_FAILED = 'GET_USER_LIST_FAILED'
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS'


export const UPDATE_USER_PERMISSION_INIT = 'UPDATE_USER_PERMISSION_INIT'
export const UPDATE_USER_PERMISSION_FAILED = 'UPDATE_USER_PERMISSION_FAILED'
export const UPDATE_USER_PERMISSION_SUCCESS = 'UPDATE_USER_PERMISSION_SUCCESS'


export const GET_TRANSACTION_LIST_INIT = 'GET_TRANSACTION_LIST_INIT'
export const GET_TRANSACTION_LIST_FAILED = 'GET_TRANSACTION_LIST_FAILED'
export const GET_TRANSACTION_LIST_SUCCESS = 'GET_TRANSACTION_LIST_SUCCESS'



export const  APPROVE_TRXN_INIT = ' APPROVE_TRXN_INIT'
export const  APPROVE_TRXN_FAILED = ' APPROVE_TRXN_FAILED'
export const APPROVE_TRXN_SUCCESS = ' APPROVE_TRXN_SUCCESS'



export const FETCH_GLOBAL_RATE_INIT = 'FETCH_GLOBAL_RATE_INIT'
export const FETCH_GLOBAL_RATE_SUCCESS = 'FETCH_GLOBAL_RATE_SUCCESS'
export const FETCH_GLOBAL_RATE_FAILURE = 'FETCH_GLOBAL_RATE_FAILURE'


export const FETCH_USER_DATA_INIT = 'FETCH_USER_DATA_INIT'
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS'
export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE'

export const UPDATE_PRODUCT_RATE_INIT = 'UPDATE_PRODUCT_RATE_INIT'
export const UPDATE_PRODUCT_RATE_FAILED = 'UPDATE_PRODUCT_RATE_FAILED'
export const UPDATE_PRODUCT_RATE_SUCCESS = 'UPDATE_PRODUCT_RATE_SUCCESS'

export const FETCH_PRODUCT_RATE_INIT = 'FETCH_PRODUCT_RATE_INIT'
export const FETCH_PRODUCT_RATE_FAILED = 'FETCH_PRODUCT_RATE_FAILED'
export const FETCH_PRODUCT_RATE_SUCCESS = 'FETCH_PRODUCT_RATE_SUCCESS'
