export default Object.freeze({

   LOGIN : 'LOGIN',
   SIGNUP : 'SIGNUP',
   LISTINGS : 'LISTINGS',
   APPROVALS : 'APPROVALS',
   OPEN_REQUEST : 'OPEN_REQUEST',
   PERMISSIONS : 'PERMISSIONS',
   HOME:'HOME',
   PROFILE : 'PROFILE'


});